### ISSUE TITLE
Return coordinates starting from 0,0

### ISSUE THREAD

**Issue by emeeks** [Klortho/d3-flextree#14]
As it stands, flextree seems to return centered coordinates. It would be more keeping with the other d3-hierarchy style layouts if it instead returned coordinates that started from 0,0 (including the width and height of the calculated nodes). If this is an option or I shouldn't be seeing negative x values, let me know.

**Comment by michaeljohansen** [comment]
If the root node starts at 0,0 then you should be seeing negative X values in a tree with children. Pretty sure this is how D3 Hierarchy works as well, also with centred coords. Width and height of calculated nodes is available inside `node.data.size`, which is the size one has provided for the layout.

**Comment by Klortho** [comment]
If I get to it, I'll try to make it more clear in the docs.
