### ISSUE TITLE
overlapping in tree nodes with different sizes

### ISSUE THREAD

**Issue by salehmosleh** [Klortho/d3-flextree#16]
This tree with different node sizes like below makes overlapping!

> const flextree = require('d3-flextree').flextree;
> const layout = flextree();
> const tree = layout.hierarchy({
>   id:1,
>   size: [1, 1],
>   children: [
>     {id:2, size: [2, 1], children: [ ]},
>     {id:3, size: [4, 1], children: [ ]},
>     {id:4, size: [1, 1], children: [ ]}
>   ]
> });
> layout(tree);
> tree.each(node => console.log(`(${node.x}, ${node.y})`));

when we run this code, you can see calculate wrong X for nodes with id 2 and 3!
the result:

> "(0, 0)"
> "(-2.5, 1)"
> "(0.5, 1)"
> "(3, 1)"

the excepted result:

> "(0, 0)"
> "(-3, 1)"
> "(-1, 1)"
> "(3, 1)"

**Comment by reaIws** [comment]
I also encountered this problem, so how do you deal with it

**Comment by reaIws** [comment]
![image](https://user-images.githubusercontent.com/23316065/84725845-235a7800-afbe-11ea-8fe7-d525c790ea37.png)

**Comment by reaIws** [comment]
i think i get it。the positoin of d3-flextree  is the center of the area. not the start of the area.

**Comment by Klortho** [comment]
As realws says, the x-coordinate is for the center of each node, whereas the y-coordinate is for the top (assuming a vertical layout). Sorry for the inconsistency!
