### ISSUE TITLE
Is possible to get a new version published in NPM registry ?

### ISSUE THREAD

**Issue by deiv** [Klortho/d3-flextree#21]
As the title suggest, for working with latest versions of webpack, the commit fe0156836a22bf71fed142f41accc4db1a188cdf is needed.

Thanks !

**Comment by sidyes** [comment]
That would really be awesone as I also want to use this to work wiht webpack 5.

**Comment by eckseller** [comment]
How can we use the a specific commit like fe01568 from @avs-doom in my dependencies in node. I'm installing a package via "npm i d3-org-chart" and it depends on d3-flextree. But it's using an older release in NPM, which doesn't include the webpack 5 bug fixes that are in the latest commits. Any help greatly appreciated, thanks

**Comment by bengray2** [comment]
Just leaving a little bread crumb for the next unsuspecting dev, when you get the following error when using ng build this is why. 

`./node_modules/d3-flextree/src/flextree.js:172:19-26 - Error: Should not import the named export 'version' (imported as 'version') from default-exporting module (only default export is available soon)`

You can go into ./node_modules/d3-flextree/src/flextree.js:172:19-26 and make the changes in https://github.com/Klortho/d3-flextree/commit/fe0156836a22bf71fed142f41accc4db1a188cdf manually, until the NPM package is updated. 

Hope that helps somebody.

**Comment by bumbeishvili** [comment]
What about taking d3 flextree and publishing it as a separate flextree module with mentioned changes made?

I could then reference that package as a dependency

**Comment by bengray2** [comment]
> What about taking d3 flextree and publishing it as a separate flextree module with mentioned changes made?
> 
> I could then reference that package as a dependency

I've done something like that, and it worked.   I forked the project to https://github.com/bengray2/d3-flextree.  Then I fixed some linting issues which broke the build and removed the 'clean' step from package.json (because it used rm which breaks on Windows).

Then I ran `npm install github.com/bengray2/d3-flextree` (or you can just add `"d3-flextree": "github:bengray2/d3-flextree"` to package.json).   Obviously all a work around until d3-flextree NPM is updated.

**Comment by eckseller** [comment]
@bengray2 @bumbeishvili I did the same thing, first I forked the d3-flextree report to my own repo, made the changes then created a pull request so it could be merged back to official d3-flextree repo, however not sure the owner of the repo is very active as hasn't been merged yet :p

**Comment by Klortho** [comment]
I think I got it published, new version 2.1.2.
Sorry for the delay, but I am not able to function as I used to, because reasons.
