### ISSUE TITLE
Top to Bottom

### ISSUE THREAD

**Issue by niksa88** [Klortho/d3-flextree#5]
Hi,

Is it possible to flip tree top to bottom?

Thanks a lot.

**Comment by Klortho** [comment]
Sure, why not?

**Comment by niksa88** [comment]
I trying on demo but elements always flying all over the place. 

I  turned transform
`    node.attr("transform", function(d) {
        return "translate(" + svg_y(d.x) + "," + svg_x(d.y) + ")";
    })`
and now elements are top to bottom but they are overlapping.

Can you please help me with that problem?
