### ISSUE TITLE
Any plans on calling for new maintainers?

### ISSUE THREAD

**Issue by JLHwung** [Klortho/d3-flextree#7]
As metioned in #6, d3 has released [v4.0](https://github.com/d3/d3/blob/master/CHANGES.md) and features modular library. I am happy to adapt this plugin to v4.0.

**Comment by Klortho** [comment]
I don't see your commits in your fork. Could you send a PR?

**Comment by timelyportfolio** [comment]
Delighted to see this https://github.com/neptunjs/d3-flextree-v4 from @neptunjs.  Happy to help also.
