### ISSUE TITLE
Custom spacing does not work

### ISSUE THREAD

**Issue by yongchul** [Klortho/d3-flextree#9]
I found that custom spacing does not work (an example layout dump is pasted at the end). I can confirm that spacing accessor is called every time but somehow does not affect the 'y' coordinates. For example, with custom spacing 10, I expect 'y' in the following (the right most leaf in the paste below would be (320, 410) instead of (320, 400) -- and this recurses of course:

                         { size: [1260, 80],
                          x: 530, y: 320,
                          children: [
                            { size: [380, 80],
                              x: 530, y: 400 },
                          ],

I can work around the problem by including the spacing (I only need fixed spacing for now) in the size but it would be nice if this is something that you can quickly fix since you have much better knowledge on this. :-)

`
{ size: [620, 60],
  x: 0, y: 0,
  children: [
    { size: [10, 40],
      x: 0, y: 60,
      children: [
        { size: [620, 60],
          x: -570, y: 100,
          children: [
            { size: [340, 60],
              x: -570, y: 160,
              children: [
                { size: [10, 40],
                  x: -570, y: 220,
                  children: [
                    { size: [480, 60],
                      x: -570, y: 260,
                      children: [
                        { size: [740, 60],
                          x: -570, y: 320,
                          children: [
                            { size: [340, 80],
                              x: -570, y: 380 },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        { size: [700, 60],
          x: 530, y: 100,
          children: [
            { size: [1200, 60],
              x: 530, y: 160,
              children: [
                { size: [560, 60],
                  x: 530, y: 220,
                  children: [
                    { size: [10, 40],
                      x: 530, y: 280,
                      children: [
                        { size: [1260, 80],
                          x: 530, y: 320,
                          children: [
                            { size: [380, 80],
                              x: 530, y: 400 },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
},`

**Comment by Klortho** [comment]
spacing doesn't effect y; it effects x. Maybe you are confused because the canonical way of arranging the tree is vertical: the root node at the top, and children layed out horizontally below their parents. That's they way the are drawn in this repo's demo and the sample in the README. But, very often they are drawn horizontally, in which case "x" is the vertical axis, and "y" is the horizontal.

Without spacing, your tree results in:

```
{ size: [620, 60],
  x: 0, y: 0,
  children: [
    { size: [10, 40],
      x: 0, y: 60,
      children: [
        { size: [620, 60],
          x: -520, y: 100,
          ...
        },
        { size: [700, 60],
          x: 480, y: 100,
          ...
        },
      ],
    },
  ],
},
```

When I layed out your tree with spacing `node => 10`, I got the following -- note the difference in `x`:

```
{ size: [620, 60],
  x: 0, y: 0,
  children: [
    { size: [10, 40],
      x: 0, y: 60,
      children: [
        { size: [620, 60],
          x: -525, y: 100,
          ...
        },
        { size: [700, 60],
          x: 485, y: 100,
          ...
        },
      ],
    },
  ],
},
```
